FROM kong/kong:3.9.1

USER root

COPY volumes/api/kong-entrypoint.sh /home/kong/kong-entrypoint.sh
COPY volumes/api/kong.yml /home/kong/temp.yml
COPY volumes/functions/main/index.ts /home/keno-functions/main/index.ts
COPY volumes/functions/hello/index.ts /home/keno-functions/hello/index.ts

RUN chmod +x /home/kong/kong-entrypoint.sh && \
    mkdir -p /home/deno/functions/main /home/deno/functions/hello && \
    cp /home/keno-functions/main/index.ts /home/deno/functions/main/index.ts && \
    cp /home/keno-functions/hello/index.ts /home/deno/functions/hello/index.ts && \
    rm -rf /home/keno-functions

USER kong
